apiVersion: v1
name: emsp-platform
version: 1.0.0
description: Helm charts for open-electrons emsp-platform project
keywords:
  - emsp-platform
  - microservice
home: https://github.com/open-electrons/eMSP-platform
maintainers:
  - name: Joesan
    email: https://github.com/joesan
    url: https://www.bigelectrons.com
