apiVersion: v1
kind: Service # This is a test
metadata:
  name: {{ .Values.grafanaService.name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /metrics
    prometheus.io/port:   '3000'
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000