apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheusService.name }}
  namespace: {{ .Values.app.namespace }}
  # namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '8080'
  
spec:
  selector: 
    app: {{ .Values.prometheusService.name }}
  type: ClusterIP  
  ports:
    - port: 8080
      targetPort: 8080