apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: emsp-platform-kustomization
resources:
  # 0. Get the namespaces first
  - application/emsp-platform-namespace.yaml

  # 1. Set up Ingress service
  - application/emsp-platform-ingress-service.yaml

  # 2. Set up the application services (backend)
  - application/emsp-platform-namespace.yaml
  - application/emsp-platform-service.yaml
  - application/emsp-platform-deployment.yaml

  # 5. Set up the application services (frontend) [[ TODO ]]